[package]
name = "oci-strace-hook"
version = "0.1.0"
authors = ["Mrunal Patel <mrunalp@gmail.com>"]

[dependencies]
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
nix = "0.9.0"
daemonize = "0.2.3"
clap = "2.29.0"
